---
env:
  contexts:
  - name: "sequence"
    urls:
    - "http://localhost:9091/seq/performance"
    includePaths:
    - "http://localhost:9091/seq/performance.*"
    excludePaths: []
  parameters:
    failOnError: true
    failOnWarning: false
    continueOnFailure: true
    progressToStdout: true
  vars: {}
jobs:
- type: sequence-import
  parameters:
    name: seq-simple
    path: /zap/wrk/configs/plans/data/seq-simple.har 
    assertCode: true
    assertLength: 10
- type: sequence-activeScan
  parameters:
    sequence: seq-simple
    context: sequence
  policyDefinition:
    defaultStrength: medium
    defaultThreshold: "off"
    rules:
    - name: Cross Site Scripting (Reflected)
      id: 40012
      threshold: medium
      strength: default
  tests:
  - name: sequence-activeScan/alert
    type: alert
    onFail: ERROR
    scanRuleId: 40012
    action: passIfPresent
