name: Handle Release

on:
  release:
    types: [published]

jobs:
  handle-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Handle Release
      run: ./gradlew handleReleaseFromGitHubRef
      env:
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
        CROWDIN_AUTH_TOKEN: ${{ secrets.ZAPBOT_CROWDIN_TOKEN }}
