name: "Pull Request Labeler"
on:
  pull_request_target:
    types:
    - opened

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      if: join(github.event.pull_request.labels) == ''
      with:
        configuration-path: .github/workflows/conf/pr-labeler.yml
