name: Run Sonar

on: 
  schedule:
    - cron: '0 15 * * SAT'
  workflow_dispatch:

jobs:
  sonar:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Gradle Test & Coverage Report
      run: ./gradlew test jacocoTestReport -Dorg.gradle.jvmargs=-Xmx4096m
    - name: Sonarcloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.ZAPBOT_SONARCLOUD_TOKEN }}
      run: ./gradlew sonar --stacktrace -Dorg.gradle.jvmargs=-Xmx4096m